# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fix-sender',
                'doc_host': 'https://jstranik.github.io',
                'git_url': 'https://github.com/jstranik/fix-sender',
                'lib_path': 'fix_sender'},
  'syms': {'fix_sender.core': {'fix_sender.core.foo': ('core.html#foo', 'fix_sender/core.py')}}}
